### ISSUE TITLE
Credit card regex is insufficient

### ISSUE THREAD

**Issue by mynamesleon** [CharlGottschalk/approvejs#2]
I tested your credit card regular expression against the examples provided here: http://www.paypalobjects.com/en_US/vhelp/paypalmanager_help/credit_card_numbers.htm

It returns false for all of the card numbers in the "Processor-specific Cards" section (76009244561, 5019717010103742, 6331101999990016), and for the 4th number in the main section (5610591081018250)

The code block I used to test them all:
```javascript
var a = '378282246310005 371449635398431 378734493671000 5610591081018250 30569309025904 38520000023237 6011111111111117 6011000990139424 3530111333300000 3566002020360505 5555555555554444 5105105105105100 4111111111111111 4012888888881881 4222222222222 76009244561 5019717010103742 6331101999990016'.split(' '),
    i;

for (i = 0; i < a.length; i += 1) {
    console.log(approve.value(a[i], { cc: true }).approved);
}
```

I should also note that in contrast, jQuery validate's interpretation of the Luhn Algorithm for credit card checking passes with all of the above numbers, except for the third to last (76009244561).

**Comment by CharlGottschalk** [comment]
Thank You @mynamesleon.

I updated the credit card test (**ApproveJs v1.0.1**), which now uses the Luhn Algorithm and successfully validates the test numbers, except for the short Dunkort number (**76009244561**), because of its length being 11 and the shortest valid card number (**Maestro**) being 12.
