### ISSUE TITLE
Use RollupJS

### ISSUE THREAD

**Issue by tjbenton** [CharlGottschalk/approvejs#5]
This isn't really an issue, just a suggestion. I would look into http://rollupjs.org/ for bundling your package instead of using gulp and concatenating parts of the file. It will make it a lot easier to manage later on without adding any bloat to your final product.

**Comment by CharlGottschalk** [comment]
Hi @tjbenton 

Thanks for the suggestion. I actually looked into RollupJS and couldn't get it to work properly. Rollup would rename variables and functions if the same variable or function was present in another module.

For instance, the `Result` function would be renamed to `Result$1` because it is called in another script.

I don't know, maybe I'm just doing something wrong, but as soon as I figure it out, or find a suitable example, I will definitely go that route. For now, I simplified the concatenation which no longer requires you to name files specifically or rename the last file to be concatenated.
